global_costmap:
    global_costmap:
        ros__parameters:
            inflation_layer:
                plugin: "nav2_costmap_2d::InflationLayer"
                cost_scaling_factor: 3.0
                inflation_radius: 0.30

local_costmap:
    local_costmap:
        ros__parameters:
            inflation_layer:
                plugin: "nav2_costmap_2d::InflationLayer"
                cost_scaling_factor: 3.0
                inflation_radius: 0.30
